// JMP database schema — the single source of truth (TRD §4, §6).
//
// Two groups:
//  1. Auth tables (user/session/account/verification) — generated by Better
//     Auth's CLI into ./auth-schema.ts, re-exported here so migrations cover
//     them. Do not hand-edit auth-schema.ts; re-run `npm run auth:generate`.
//  2. Application tables — one column per field a Phase-1 screen reads/writes.
//     `lib/types.ts` is the UI-side mirror of these shapes.
//
// Every application table carries `user_id` (text, FK → user.id) from day one
// so a future second user needs no migration; today all rows are the one owner.
// NOTE: Better Auth's default IDs are `text`, so `user_id` is text — not uuid
// as an earlier draft of the schema plan assumed.

import { sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  boolean,
  integer,
  uuid,
  date,
  timestamp,
  jsonb,
  uniqueIndex,
  index,
  customType,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Raw bytes column (node-postgres returns/accepts a Buffer).
const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return "bytea";
  },
});

// Auth tables live alongside app tables in every migration.
export * from "./auth-schema";

/* ------------------------------------------------------------------ */
/* Enums (mirror the unions in lib/types.ts)                           */
/* ------------------------------------------------------------------ */

export const leadStatus = pgEnum("lead_status", [
  "new",
  "reviewing",
  "applied",
  "discarded",
  "closed",
]);
export const closeOutcome = pgEnum("close_outcome", [
  "offer",
  "rejected",
  "withdrawn",
  "no-response",
]);
export const connectionType = pgEnum("connection_type", [
  "recruiter",
  "referral",
  "hiring-manager",
  "other",
]);
export const outreachKind = pgEnum("outreach_kind", [
  "referral-ask",
  "cold-outreach",
  "follow-up",
]);
export const outreachStatus = pgEnum("outreach_status", ["draft", "sent"]);
export const reminderOutcome = pgEnum("reminder_outcome", [
  "pending",
  "reminder-sent",
  "response-received",
  "closed",
  "not-responded",
]);
export const taskKind = pgEnum("task_kind", ["follow-up", "decision", "manual"]);
export const taskStatus = pgEnum("task_status", ["open", "done"]);
export const aiProvider = pgEnum("ai_provider", [
  "openai",
  "anthropic",
  "openrouter",
]);
export const resumeFileType = pgEnum("resume_file_type", ["pdf", "doc", "docx"]);
export const planStatus = pgEnum("plan_status", ["active", "inactive"]);

/* ------------------------------------------------------------------ */
/* Application tables                                                   */
/* ------------------------------------------------------------------ */

/** One row per parsed alert email — the automated-ingestion anchor (maps JobLead). */
export const jobLeads = pgTable(
  "job_leads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Dedupe key (FR-1.5), parsed from the canonical URL.
    linkedinJobId: text("linkedin_job_id").notNull(),
    title: text("title").notNull(),
    company: text("company").notNull(),
    location: text("location").notNull(),
    remote: boolean("remote").notNull().default(false),
    tags: text("tags").array().notNull().default(sql`'{}'::text[]`),
    postedRelative: text("posted_relative").notNull(),
    canonicalJobUrl: text("canonical_job_url").notNull(),
    status: leadStatus("status").notNull().default("new"),
    closeOutcome: closeOutcome("close_outcome"), // set only when status = closed
    capturedAt: timestamp("captured_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    // The Gmail message this lead came from, for audit / error tracing.
    sourceMessageId: text("source_message_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // Anti-flooding: a job seen again across emails/re-fetches is ignored via
    // ON CONFLICT DO NOTHING against this key (FR-1.5).
    uniqueIndex("job_leads_user_linkedin_job_id_uq").on(
      t.userId,
      t.linkedinJobId,
    ),
    index("job_leads_user_status_idx").on(t.userId, t.status),
    index("job_leads_user_captured_idx").on(t.userId, t.capturedAt.desc()),
    index("job_leads_tags_gin_idx").using("gin", t.tags),
  ],
);

/** Full JD text, AI summary, and notes — 1:1 with a lead (maps JobLeadDetail). */
export const jobLeadDetails = pgTable("job_lead_details", {
  leadId: uuid("lead_id")
    .primaryKey()
    .references(() => jobLeads.id, { onDelete: "cascade" }),
  // Direct owner scoping (in addition to lead_id → job_leads) so every write
  // carries user_id and reads can filter by it (multi-user).
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  jdText: text("jd_text"),
  aiSummary: text("ai_summary"),
  notes: text("notes"),
});

/** Recruiter / referral contacts tied to a lead (maps Contact). */
export const contacts = pgTable(
  "contacts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    title: text("title").notNull().default(""),
    linkedinUrl: text("linkedin_url"),
    connectionType: connectionType("connection_type").notNull(),
    aiParsed: boolean("ai_parsed").notNull().default(false),
    // Orders "contact added" events in the per-lead timeline (FR-6.2).
    addedAt: timestamp("added_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index("contacts_lead_idx").on(t.leadId),
    // Groups a person across leads for per-contact history (FR-6.1).
    index("contacts_user_linkedin_url_idx").on(t.userId, t.linkedinUrl),
  ],
);

/** AI draft + final sent message per contact (maps OutreachMessage). Stores
 *  both bodies for record-keeping (FR-4.4). */
export const outreachMessages = pgTable(
  "outreach_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    kind: outreachKind("kind").notNull(),
    channel: text("channel").notNull(),
    status: outreachStatus("status").notNull().default("draft"),
    draftBody: text("draft_body").notNull(),
    sentBody: text("sent_body"),
    resumeId: uuid("resume_id").references(() => resumes.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    sentAt: timestamp("sent_at", { withTimezone: true }),
  },
  (t) => [
    index("outreach_lead_idx").on(t.leadId),
    index("outreach_contact_idx").on(t.contactId),
  ],
);

/** Follow-up schedule + outcome per outreach message (maps Reminder). */
export const reminders = pgTable(
  "reminders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    // Null for a manual reminder not tied to a specific sent message.
    outreachMessageId: uuid("outreach_message_id").references(
      () => outreachMessages.id,
      { onDelete: "set null" },
    ),
    sequence: integer("sequence").notNull(),
    // Full timestamp (date + time) so reminders can be scheduled for a time of
    // day, not just a day.
    dueDate: timestamp("due_date", { withTimezone: true, mode: "string" }).notNull(),
    outcome: reminderOutcome("outcome").notNull().default("pending"),
    manual: boolean("manual").notNull().default(false),
    label: text("label"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // Drives the daily due-check cron (TRD §9).
    index("reminders_user_outcome_due_idx").on(t.userId, t.outcome, t.dueDate),
    index("reminders_lead_idx").on(t.leadId),
  ],
);

/** The actionable To-do item; always tied to a job, optionally to a reminder
 *  (maps Task). UI-revealed addition — see the schema plan's Deviations. */
export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    jobId: uuid("job_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    reminderId: uuid("reminder_id").references(() => reminders.id, {
      onDelete: "set null",
    }),
    title: text("title").notNull(),
    kind: taskKind("kind").notNull(),
    dueDate: date("due_date", { mode: "string" }),
    status: taskStatus("status").notNull().default("open"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    index("tasks_user_status_due_idx").on(t.userId, t.status, t.dueDate),
    index("tasks_job_idx").on(t.jobId),
  ],
);

/** Uploaded resume files to draft against / score fit with (maps Resume). */
export const resumes = pgTable(
  "resumes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    fileName: text("file_name").notNull(),
    fileType: resumeFileType("file_type").notNull(),
    sizeKb: integer("size_kb").notNull(),
    // Phase 3: file lives in blob storage (Vercel Blob/S3/R2) — the Vercel FS
    // is read-only, so we store a URL, not bytes.
    blobUrl: text("blob_url").notNull(),
    // Pasted plain-text of the resume, used by AI fit-scoring (null until the
    // user adds it in Settings).
    resumeText: text("resume_text"),
    isDefault: boolean("is_default").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // At most one default resume per user.
    uniqueIndex("resumes_one_default_per_user_uq")
      .on(t.userId)
      .where(sql`${t.isDefault}`),
  ],
);

/** One settings row per user — backs Settings → Follow-ups + AI provider. */
export const userSettings = pgTable("user_settings", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  reminderIntervalDays: integer("reminder_interval_days").notNull().default(3), // FR-5.1
  staleLeadDays: integer("stale_lead_days").notNull().default(14), // FR-2.4
  // How often the Gmail sync should run for this user (hours): 24/12/6/3/1.
  syncIntervalHours: integer("sync_interval_hours").notNull().default(24),
  defaultResumeId: uuid("default_resume_id").references(() => resumes.id, {
    onDelete: "set null",
  }),
  aiProvider: aiProvider("ai_provider").notNull().default("openai"),
  aiModel: text("ai_model"),
  // Encrypted at rest (TRD §8). Stored as base64(ciphertext); only the last 4
  // chars are ever returned to the client.
  aiKeyCiphertext: text("ai_key_ciphertext"),
  aiKeyLast4: text("ai_key_last4"),
  // User-customized AI instruction prompts (null = use the built-in default).
  promptSummary: text("prompt_summary"),
  promptDraft: text("prompt_draft"),
  promptScore: text("prompt_score"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/**
 * The uploaded résumé file bytes, kept out of the resumes table so they're
 * never pulled into a workspace read. One file per résumé (stored in Postgres
 * for now; swap to blob storage at go-live). Text is extracted at upload and
 * lives in resumes.resume_text.
 */
export const resumeFiles = pgTable("resume_files", {
  resumeId: uuid("resume_id")
    .primaryKey()
    .references(() => resumes.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  contentType: text("content_type").notNull(),
  data: bytea("data").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Cached AI fit score for a (lead, resume) pair. Computed on demand (never
 * automatically), so the UI shows "NC" until the user triggers a score/rescore.
 * One row per (user, lead, resume); a rescore overwrites it.
 */
export const fitScores = pgTable(
  "fit_scores",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    resumeId: uuid("resume_id")
      .notNull()
      .references(() => resumes.id, { onDelete: "cascade" }),
    score: integer("score").notNull(),
    rationale: text("rationale"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    uniqueIndex("fit_scores_user_lead_resume_uq").on(
      t.userId,
      t.leadId,
      t.resumeId,
    ),
  ],
);

/**
 * App-level SMTP settings for outbound system email (password resets). A single
 * row (id = "app"); a future admin dashboard edits it. The password is
 * encrypted at rest (lib/crypto), like the AI key.
 */
export const smtpConfig = pgTable("smtp_config", {
  id: text("id").primaryKey().default("app"),
  host: text("host").notNull(),
  port: integer("port").notNull().default(587),
  // Legacy boolean kept for the current mailer; `encryption` is the richer choice
  // the admin UI writes (none/starttls/ssl/tls). Mailer reads encryption when set.
  secure: boolean("secure").notNull().default(false),
  encryption: text("encryption").notNull().default("starttls"),
  username: text("username"),
  passwordCiphertext: text("password_ciphertext"),
  fromEmail: text("from_email").notNull(),
  fromName: text("from_name"),
  replyTo: text("reply_to"),
  enabled: boolean("enabled").notNull().default(false),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/* ------------------------------------------------------------------ */
/* Admin: Plans & Pricing + app-level config (single "app" row each)    */
/* ------------------------------------------------------------------ */

/** Subscription plans shown on the admin Plans & Pricing screen. */
export const plans = pgTable("plans", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  code: text("code").notNull().unique(),
  // Rich-text HTML from the admin editor (sanitize on write when wired).
  description: text("description").notNull().default(""),
  accent: text("accent").notNull().default("indigo"),
  isFree: boolean("is_free").notNull().default(false),
  // Free plan only — days of access before renewal (0 = never expires).
  freeDurationDays: integer("free_duration_days").notNull().default(0),
  // 0 disables that interval.
  monthlyPrice: integer("monthly_price").notNull().default(0),
  yearlyPrice: integer("yearly_price").notNull().default(0),
  currency: text("currency").notNull().default("INR"),
  // null = unlimited.
  limitResumes: integer("limit_resumes"),
  allowCustomPrompts: boolean("allow_custom_prompts").notNull().default(false),
  features: text("features").array().notNull().default(sql`'{}'::text[]`),
  popular: boolean("popular").notNull().default(false),
  status: planStatus("status").notNull().default("active"),
  // Running count of users who have ever been on this plan — gates deletion.
  everSubscribed: integer("ever_subscribed").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Branding assets (logo, favicon) the admin can change anytime. One row per
 *  kind; bytes stored in-DB (small, few) and served via /api/branding/[kind].
 *  When a kind has no row, the app falls back to its built-in default. */
export const appAssets = pgTable("app_assets", {
  kind: text("kind").primaryKey(), // "logo" | "favicon"
  contentType: text("content_type").notNull(),
  data: bytea("data").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Settings → General (one "app" row). */
export const appSettings = pgTable("app_settings", {
  id: text("id").primaryKey().default("app"),
  appName: text("app_name").notNull().default("Job Management Portal"),
  supportEmail: text("support_email"),
  allowSignup: boolean("allow_signup").notNull().default(false),
  maintenance: boolean("maintenance").notNull().default(false),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Settings → Security (one "app" row). Password policy + session length. */
export const securityConfig = pgTable("security_config", {
  id: text("id").primaryKey().default("app"),
  pwMinLength: integer("pw_min_length").notNull().default(8),
  pwRequireUpper: boolean("pw_require_upper").notNull().default(true),
  pwRequireLower: boolean("pw_require_lower").notNull().default(true),
  pwRequireNumber: boolean("pw_require_number").notNull().default(true),
  pwRequireSpecial: boolean("pw_require_special").notNull().default(true),
  sessionValue: integer("session_value").notNull().default(7),
  sessionUnit: text("session_unit").notNull().default("days"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Settings → Cron & schedule (one "app" row). */
export const cronConfig = pgTable("cron_config", {
  id: text("id").primaryKey().default("app"),
  quietEnabled: boolean("quiet_enabled").notNull().default(false),
  quietFrom: text("quiet_from").notNull().default("22:00"),
  quietTo: text("quiet_to").notNull().default("07:00"),
  quietTz: text("quiet_tz").notNull().default("Asia/Kolkata"),
  quietDays: text("quiet_days").array().notNull().default(sql`'{}'::text[]`),
  purgeEnabled: boolean("purge_enabled").notNull().default(false),
  purgeDays: integer("purge_days").notNull().default(90),
  purgeStatuses: text("purge_statuses").array().notNull().default(sql`'{}'::text[]`),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Audit log of automatic stale-lead purges, per user per run. Records the policy
 *  in force (days + statuses) and how many leads were deleted per status, so each
 *  deletion is accountable and the user can be notified. */
export const leadPurgeLog = pgTable(
  "lead_purge_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    runAt: timestamp("run_at", { withTimezone: true }).notNull().defaultNow(),
    policyDays: integer("policy_days").notNull(),
    statuses: text("statuses").array().notNull().default(sql`'{}'::text[]`),
    // { [status]: count } of leads deleted in this run.
    counts: jsonb("counts").$type<Record<string, number>>().notNull(),
    totalDeleted: integer("total_deleted").notNull(),
    notified: boolean("notified").notNull().default(false),
  },
  (t) => [index("lead_purge_log_user_idx").on(t.userId, t.runAt.desc())],
);

/** Settings → Billing (one "app" row). Gateway secret encrypted at rest. */
export const billingConfig = pgTable("billing_config", {
  id: text("id").primaryKey().default("app"),
  enabled: boolean("enabled").notNull().default(false),
  provider: text("provider").notNull().default("razorpay"),
  mode: text("mode").notNull().default("test"),
  currency: text("currency").notNull().default("INR"),
  keyId: text("key_id"),
  keySecretCiphertext: text("key_secret_ciphertext"),
  gstin: text("gstin"),
  taxRate: integer("tax_rate").notNull().default(18),
  pricesIncludeTax: boolean("prices_include_tax").notNull().default(false),
  companyName: text("company_name"),
  companyAddress: text("company_address"),
  invoicePrefix: text("invoice_prefix").notNull().default("JMP-"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Settings → AI (one "app" row). Admin tools AI key + default user prompts. */
export const appAiConfig = pgTable("app_ai_config", {
  id: text("id").primaryKey().default("app"),
  adminProvider: aiProvider("admin_provider").notNull().default("openai"),
  adminModel: text("admin_model"),
  adminKeyCiphertext: text("admin_key_ciphertext"),
  adminKeyLast4: text("admin_key_last4"),
  defaultPromptSummary: text("default_prompt_summary"),
  defaultPromptDraft: text("default_prompt_draft"),
  defaultPromptScore: text("default_prompt_score"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** One row per user — the Gmail ingestion rules (Settings → Which emails to read). */
export const gmailConfig = pgTable("gmail_config", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  senders: text("senders").array().notNull().default(sql`'{}'::text[]`),
  label: text("label"),
  subjectKeywords: text("subject_keywords"),
  lookbackDays: integer("lookback_days").notNull().default(30),
  connected: boolean("connected").notNull().default(false),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** One row per user — the incremental Gmail sync cursor (TRD §9). */
export const gmailSyncState = pgTable("gmail_sync_state", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  lastHistoryId: text("last_history_id"),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  lastError: text("last_error"),
});

/** Parse failures land here instead of being silently dropped (FR-1.7). */
export const gmailIngestErrors = pgTable("gmail_ingest_errors", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  messageId: text("message_id").notNull(),
  reason: text("reason").notNull(),
  rawExcerpt: text("raw_excerpt"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/** Message-level dedupe so a re-delivered email isn't re-parsed. Belt-and-braces
 *  — the linkedin_job_id unique key already prevents duplicate leads. */
export const gmailProcessedMessages = pgTable(
  "gmail_processed_messages",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    messageId: text("message_id").notNull(),
    processedAt: timestamp("processed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("gmail_processed_messages_pk").on(t.userId, t.messageId),
  ],
);
