// JMP database schema — the single source of truth (TRD §4, §6).
//
// Two groups:
//  1. Auth tables (user/session/account/verification) — generated by Better
//     Auth's CLI into ./auth-schema.ts, re-exported here so migrations cover
//     them. Do not hand-edit auth-schema.ts; re-run `npm run auth:generate`.
//  2. Application tables — one column per field a Phase-1 screen reads/writes.
//     `lib/types.ts` is the UI-side mirror of these shapes.
//
// Every application table carries `user_id` (text, FK → user.id) from day one
// so a future second user needs no migration; today all rows are the one owner.
// NOTE: Better Auth's default IDs are `text`, so `user_id` is text — not uuid
// as an earlier draft of the schema plan assumed.

import { sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  text,
  boolean,
  integer,
  uuid,
  date,
  timestamp,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Auth tables live alongside app tables in every migration.
export * from "./auth-schema";

/* ------------------------------------------------------------------ */
/* Enums (mirror the unions in lib/types.ts)                           */
/* ------------------------------------------------------------------ */

export const leadStatus = pgEnum("lead_status", [
  "new",
  "reviewing",
  "applied",
  "discarded",
  "closed",
]);
export const closeOutcome = pgEnum("close_outcome", [
  "offer",
  "rejected",
  "withdrawn",
  "no-response",
]);
export const connectionType = pgEnum("connection_type", [
  "recruiter",
  "referral",
  "hiring-manager",
  "other",
]);
export const outreachKind = pgEnum("outreach_kind", [
  "referral-ask",
  "cold-outreach",
  "follow-up",
]);
export const outreachStatus = pgEnum("outreach_status", ["draft", "sent"]);
export const reminderOutcome = pgEnum("reminder_outcome", [
  "pending",
  "reminder-sent",
  "response-received",
  "closed",
  "not-responded",
]);
export const taskKind = pgEnum("task_kind", ["follow-up", "decision", "manual"]);
export const taskStatus = pgEnum("task_status", ["open", "done"]);
export const aiProvider = pgEnum("ai_provider", [
  "openai",
  "anthropic",
  "openrouter",
]);
export const resumeFileType = pgEnum("resume_file_type", ["pdf", "doc", "docx"]);

/* ------------------------------------------------------------------ */
/* Application tables                                                   */
/* ------------------------------------------------------------------ */

/** One row per parsed alert email — the automated-ingestion anchor (maps JobLead). */
export const jobLeads = pgTable(
  "job_leads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Dedupe key (FR-1.5), parsed from the canonical URL.
    linkedinJobId: text("linkedin_job_id").notNull(),
    title: text("title").notNull(),
    company: text("company").notNull(),
    location: text("location").notNull(),
    remote: boolean("remote").notNull().default(false),
    tags: text("tags").array().notNull().default(sql`'{}'::text[]`),
    postedRelative: text("posted_relative").notNull(),
    canonicalJobUrl: text("canonical_job_url").notNull(),
    status: leadStatus("status").notNull().default("new"),
    closeOutcome: closeOutcome("close_outcome"), // set only when status = closed
    capturedAt: timestamp("captured_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    // The Gmail message this lead came from, for audit / error tracing.
    sourceMessageId: text("source_message_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // Anti-flooding: a job seen again across emails/re-fetches is ignored via
    // ON CONFLICT DO NOTHING against this key (FR-1.5).
    uniqueIndex("job_leads_user_linkedin_job_id_uq").on(
      t.userId,
      t.linkedinJobId,
    ),
    index("job_leads_user_status_idx").on(t.userId, t.status),
    index("job_leads_user_captured_idx").on(t.userId, t.capturedAt.desc()),
    index("job_leads_tags_gin_idx").using("gin", t.tags),
  ],
);

/** Full JD text, AI summary, and notes — 1:1 with a lead (maps JobLeadDetail). */
export const jobLeadDetails = pgTable("job_lead_details", {
  leadId: uuid("lead_id")
    .primaryKey()
    .references(() => jobLeads.id, { onDelete: "cascade" }),
  // Direct owner scoping (in addition to lead_id → job_leads) so every write
  // carries user_id and reads can filter by it (multi-user).
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  jdText: text("jd_text"),
  aiSummary: text("ai_summary"),
  notes: text("notes"),
});

/** Recruiter / referral contacts tied to a lead (maps Contact). */
export const contacts = pgTable(
  "contacts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    title: text("title").notNull().default(""),
    linkedinUrl: text("linkedin_url"),
    connectionType: connectionType("connection_type").notNull(),
    aiParsed: boolean("ai_parsed").notNull().default(false),
    // Orders "contact added" events in the per-lead timeline (FR-6.2).
    addedAt: timestamp("added_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    index("contacts_lead_idx").on(t.leadId),
    // Groups a person across leads for per-contact history (FR-6.1).
    index("contacts_user_linkedin_url_idx").on(t.userId, t.linkedinUrl),
  ],
);

/** AI draft + final sent message per contact (maps OutreachMessage). Stores
 *  both bodies for record-keeping (FR-4.4). */
export const outreachMessages = pgTable(
  "outreach_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
      .notNull()
      .references(() => contacts.id, { onDelete: "cascade" }),
    kind: outreachKind("kind").notNull(),
    channel: text("channel").notNull(),
    status: outreachStatus("status").notNull().default("draft"),
    draftBody: text("draft_body").notNull(),
    sentBody: text("sent_body"),
    resumeId: uuid("resume_id").references(() => resumes.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    sentAt: timestamp("sent_at", { withTimezone: true }),
  },
  (t) => [
    index("outreach_lead_idx").on(t.leadId),
    index("outreach_contact_idx").on(t.contactId),
  ],
);

/** Follow-up schedule + outcome per outreach message (maps Reminder). */
export const reminders = pgTable(
  "reminders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    // Null for a manual reminder not tied to a specific sent message.
    outreachMessageId: uuid("outreach_message_id").references(
      () => outreachMessages.id,
      { onDelete: "set null" },
    ),
    sequence: integer("sequence").notNull(),
    dueDate: date("due_date", { mode: "string" }).notNull(),
    outcome: reminderOutcome("outcome").notNull().default("pending"),
    manual: boolean("manual").notNull().default(false),
    label: text("label"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // Drives the daily due-check cron (TRD §9).
    index("reminders_user_outcome_due_idx").on(t.userId, t.outcome, t.dueDate),
    index("reminders_lead_idx").on(t.leadId),
  ],
);

/** The actionable To-do item; always tied to a job, optionally to a reminder
 *  (maps Task). UI-revealed addition — see the schema plan's Deviations. */
export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    jobId: uuid("job_id")
      .notNull()
      .references(() => jobLeads.id, { onDelete: "cascade" }),
    reminderId: uuid("reminder_id").references(() => reminders.id, {
      onDelete: "set null",
    }),
    title: text("title").notNull(),
    kind: taskKind("kind").notNull(),
    dueDate: date("due_date", { mode: "string" }),
    status: taskStatus("status").notNull().default("open"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    index("tasks_user_status_due_idx").on(t.userId, t.status, t.dueDate),
    index("tasks_job_idx").on(t.jobId),
  ],
);

/** Uploaded resume files to draft against / score fit with (maps Resume). */
export const resumes = pgTable(
  "resumes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    fileName: text("file_name").notNull(),
    fileType: resumeFileType("file_type").notNull(),
    sizeKb: integer("size_kb").notNull(),
    // Phase 3: file lives in blob storage (Vercel Blob/S3/R2) — the Vercel FS
    // is read-only, so we store a URL, not bytes.
    blobUrl: text("blob_url").notNull(),
    isDefault: boolean("is_default").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // At most one default resume per user.
    uniqueIndex("resumes_one_default_per_user_uq")
      .on(t.userId)
      .where(sql`${t.isDefault}`),
  ],
);

/** One settings row per user — backs Settings → Follow-ups + AI provider. */
export const userSettings = pgTable("user_settings", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  reminderIntervalDays: integer("reminder_interval_days").notNull().default(3), // FR-5.1
  staleLeadDays: integer("stale_lead_days").notNull().default(14), // FR-2.4
  // How often the Gmail sync should run for this user (hours): 24/12/6/3/1.
  syncIntervalHours: integer("sync_interval_hours").notNull().default(24),
  defaultResumeId: uuid("default_resume_id").references(() => resumes.id, {
    onDelete: "set null",
  }),
  aiProvider: aiProvider("ai_provider").notNull().default("openai"),
  aiModel: text("ai_model"),
  // Encrypted at rest (TRD §8). Stored as base64(ciphertext); only the last 4
  // chars are ever returned to the client.
  aiKeyCiphertext: text("ai_key_ciphertext"),
  aiKeyLast4: text("ai_key_last4"),
  // User-customized AI instruction prompts (null = use the built-in default).
  promptSummary: text("prompt_summary"),
  promptDraft: text("prompt_draft"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** One row per user — the Gmail ingestion rules (Settings → Which emails to read). */
export const gmailConfig = pgTable("gmail_config", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  senders: text("senders").array().notNull().default(sql`'{}'::text[]`),
  label: text("label"),
  subjectKeywords: text("subject_keywords"),
  lookbackDays: integer("lookback_days").notNull().default(30),
  connected: boolean("connected").notNull().default(false),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** One row per user — the incremental Gmail sync cursor (TRD §9). */
export const gmailSyncState = pgTable("gmail_sync_state", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  lastHistoryId: text("last_history_id"),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  lastError: text("last_error"),
});

/** Parse failures land here instead of being silently dropped (FR-1.7). */
export const gmailIngestErrors = pgTable("gmail_ingest_errors", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  messageId: text("message_id").notNull(),
  reason: text("reason").notNull(),
  rawExcerpt: text("raw_excerpt"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/** Message-level dedupe so a re-delivered email isn't re-parsed. Belt-and-braces
 *  — the linkedin_job_id unique key already prevents duplicate leads. */
export const gmailProcessedMessages = pgTable(
  "gmail_processed_messages",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    messageId: text("message_id").notNull(),
    processedAt: timestamp("processed_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("gmail_processed_messages_pk").on(t.userId, t.messageId),
  ],
);
